name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *" # Executa a cada 12 horas
  workflow_dispatch: # Permite execução manual

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Gera a animação da cobra
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: megonx # Substitua pelo seu nome de usuário
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Publica a imagem SVG no branch "output"
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Token gerado automaticamente
